### ISSUE TITLE
Actor

### ISSUE THREAD

**Issue by pervyrogue** [expanded-mod-team/RL-Expanded-Rewrite#30]
ADVCharacter needs extended into a Girl class for interact-able characters.

**Girl Class should:**
- [ ] Hold girl stats
- [ ] Hold current outfit
- [ ] Hold current hair
- [ ] Hold current body color
- [ ] Handle stat changes
- [ ] Handle stat checks

**Comment by pervyrogue** [comment]
Split out #3 into Girl and Player. Moved task list.

**Comment by TrainDoctor** [comment]
Proposal:

Rename and rephrase "Girls" class to be something along the lines of ActorCharacter (or vice versa) or something similar. This leaves open the possibility of the player being female and also allows for better (at a code level) support for creating LGBTQIA+ as well as non-binary characters etc. This may not be directly relevant to the project but if we lay out this ground work I think it will pay off for any projects that build off of our work etc.

**Comment by pervyrogue** [comment]
Merged into #3
