### ISSUE TITLE
Setup Submodule for Images

### ISSUE THREAD

**Issue by TrainDoctor** [expanded-mod-team/RL-Expanded-Rewrite#81]
tl;dr
A git repo should be setup to host images (webp for easy of transfer) that will be added as a submodule to this repo.
The image submodule will only be allowed to be pulled by members of the dev team to avoid distributing "pre-release" materials.

I'll expand on this soon.™️

**Comment by Mederic64** [comment]
Uploading images on github is not ideal, for space reasons... also, github won't accept nsfw pics.
