### ISSUE TITLE
Discussion: Actor Clothing Layers

### ISSUE THREAD

**Issue by TrainDoctor** [expanded-mod-team/RL-Expanded-Rewrite#84]
<details> <summary>Misc Info</summary>
This issues closes #73.
</details>

This will need clarification from @pervyrogue about what direction (0-7 or 7-0) the priority will go in (what is always on top vs what will always be hidden by those above it).
All actor layers (as currently defined in the code) look like this;

- 0 panties
- 1 bra
- 2 legs (hose)
- 3 inner (inner shirt/top layer)
- 4 bottom
- 5 dress
- 6 top
- 7 outer

The actors branch will have the latest changes related to these layers.

Please discuss any suggestions/changes for Actor clothing layers in this issue.

**Comment by Taharka** [comment]
Talking to artists now about what additional layers we want and order.

**Comment by pervyrogue** [comment]
Discussion as is should be in #40 or #73.

This is (or should be) about having these named values accessible via Actor. For ease of script writing this would be preferred so writers can use Actor.piece in dialogue or checks. Because strings are immutable, something clever may need done.
